# Generated by Django 4.1.6 on 2023-05-26 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InfluencerPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_approved", models.BooleanField(default=True)),
                ("is_posted", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True, null=True)),
                ("imageURL", models.URLField(blank=True)),
                ("videoURL", models.URLField(blank=True)),
                (
                    "influencer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="influencer_postings",
                        to="users.influencer",
                    ),
                ),
                (
                    "product_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="influencer_postings",
                        to="products.productpost",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="influencer",
            name="product_posts",
        ),
        migrations.AddField(
            model_name="influencer",
            name="product_posts",
            field=models.ManyToManyField(
                related_name="influencers",
                through="users.InfluencerPosting",
                to="products.ProductPost",
            ),
        ),
    ]
