# Generated by Django 4.1.6 on 2023-06-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="account_holder",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="brand",
            name="acount_number",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="brand",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="brand",
            name="brand_imageURL",
            field=models.ImageField(blank=True, null=True, upload_to="brand_logo"),
        ),
        migrations.AlterField(
            model_name="brand",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
