# Generated by Django 4.1.6 on 2023-05-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_influencerposting_alter_influencer_product_posts"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mileage",
            field=models.IntegerField(default=0),
        ),
    ]
