# Generated by Django 4.1.6 on 2023-06-19 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("carts", "0001_initial"),
        ("coupons", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="preorderitem",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pre_order_items",
                to="coupons.coupon",
            ),
        ),
    ]
