# Generated by Django 4.1.6 on 2023-05-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("carts", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="like",
            name="product_post",
            field=models.ManyToManyField(
                related_name="likes", to="products.productpost"
            ),
        ),
    ]
