# Generated by Django 4.1.6 on 2023-06-19 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("coupons", "0001_initial"),
        ("carts", "0002_initial"),
        ("products", "0001_initial"),
        ("users", "0001_initial"),
        ("shipments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="preorderitem",
            name="influencer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pre_order_items",
                to="users.influencer",
            ),
        ),
        migrations.AddField(
            model_name="preorderitem",
            name="pre_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="carts.preorder",
            ),
        ),
        migrations.AddField(
            model_name="preorderitem",
            name="product_post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pre_order_items",
                to="products.productpost",
            ),
        ),
        migrations.AddField(
            model_name="preorder",
            name="influencer_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pre_orders",
                to="users.influencer",
            ),
        ),
        migrations.AddField(
            model_name="preorder",
            name="shipments",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pre_orders",
                to="shipments.shipment",
            ),
        ),
        migrations.AddField(
            model_name="preorder",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pre_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="like",
            name="product_post",
            field=models.ManyToManyField(
                related_name="likes", to="products.productpost"
            ),
        ),
        migrations.AddField(
            model_name="like",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items_in_cart",
                to="carts.cart",
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="coupons.coupon",
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="influencer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carts",
                to="users.influencer",
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="product_post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="products.productpost",
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="cart_items",
            field=models.ManyToManyField(related_name="carts", to="carts.cartitem"),
        ),
        migrations.AddField(
            model_name="cart",
            name="shipments",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carts",
                to="shipments.shipment",
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
