# Generated by Django 4.1.6 on 2023-05-29 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("coupons", "0003_remove_coupon_brand_coupon_brands_coupon_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("carts", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="coupons.coupon",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
