# Generated by Django 4.1.6 on 2023-05-31 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("carts", "0004_cartitem_coupon_alter_cart_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="cart_items",
            field=models.ManyToManyField(related_name="carts", to="carts.cartitem"),
        ),
        migrations.AddField(
            model_name="cart",
            name="total_weight",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items_in_cart",
                to="carts.cart",
            ),
        ),
    ]
