# Generated by Django 4.1.6 on 2023-05-31 02:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carts", "0005_cart_cart_items_cart_total_weight_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="total_weight",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
