# Generated by Django 4.1.6 on 2023-05-15 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sellers", "0001_initial"),
        ("referrals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="referral",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referrals",
                to="sellers.seller",
            ),
        ),
    ]
