# Generated by Django 4.1.6 on 2023-06-26 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0001_initial"),
        ("coupons", "0001_initial"),
        ("categories", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="brands",
            field=models.ManyToManyField(blank=True, to="users.brand"),
        ),
        migrations.AddField(
            model_name="coupon",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coupons",
                to="categories.category",
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="influencer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="influencer_coupons",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="product_posts",
            field=models.ManyToManyField(blank=True, to="products.productpost"),
        ),
        migrations.AddField(
            model_name="coupon",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coupons",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
