# Generated by Django 4.1.6 on 2023-05-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_mileage"),
        ("products", "0003_product_weight_remove_productpost_product_and_more"),
        ("coupons", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coupon",
            name="brand",
        ),
        migrations.AddField(
            model_name="coupon",
            name="brands",
            field=models.ManyToManyField(blank=True, to="users.brand"),
        ),
        migrations.AddField(
            model_name="coupon",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="coupon",
            name="product_posts",
            field=models.ManyToManyField(blank=True, to="products.productpost"),
        ),
        migrations.AddField(
            model_name="coupon",
            name="role",
            field=models.CharField(
                choices=[
                    ("all", "All Items"),
                    ("brand", "Specific Brands"),
                    ("product", "Specific ProductPosts"),
                ],
                default="all",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="discount_amount",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="expired_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
