# Generated by Django 4.1.6 on 2023-06-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("discount_percentage", models.PositiveIntegerField()),
                ("description", models.TextField(blank=True, null=True)),
                ("weight_100g", models.PositiveIntegerField(blank=True, null=True)),
                ("weight_200g", models.PositiveIntegerField(blank=True, null=True)),
                ("weight_300g", models.PositiveIntegerField(blank=True, null=True)),
                ("weight_400g", models.PositiveIntegerField(blank=True, null=True)),
                ("weight_500g", models.PositiveIntegerField(blank=True, null=True)),
                ("weight_600g", models.PositiveIntegerField(blank=True, null=True)),
                ("weight_700g", models.PositiveIntegerField(blank=True, null=True)),
                ("weight_800g", models.PositiveIntegerField(blank=True, null=True)),
                ("weight_900g", models.PositiveIntegerField(blank=True, null=True)),
                ("weight_1000g", models.PositiveIntegerField(blank=True, null=True)),
                ("weight_1100g", models.PositiveIntegerField(blank=True, null=True)),
                ("weight_1200g", models.PositiveIntegerField(blank=True, null=True)),
                ("weight_1300g", models.PositiveIntegerField(blank=True, null=True)),
                ("weight_1400g", models.PositiveIntegerField(blank=True, null=True)),
                ("weight_1500g", models.PositiveIntegerField(blank=True, null=True)),
                ("weight_1600g", models.PositiveIntegerField(blank=True, null=True)),
                ("weight_1700g", models.PositiveIntegerField(blank=True, null=True)),
                ("weight_1800g", models.PositiveIntegerField(blank=True, null=True)),
                ("weight_1900g", models.PositiveIntegerField(blank=True, null=True)),
                ("weight_2000g", models.PositiveIntegerField(blank=True, null=True)),
                ("weight_2100g", models.PositiveIntegerField(blank=True, null=True)),
                ("weight_2200g", models.PositiveIntegerField(blank=True, null=True)),
                ("weight_2300g", models.PositiveIntegerField(blank=True, null=True)),
                ("weight_2400g", models.PositiveIntegerField(blank=True, null=True)),
                ("weight_2500g", models.PositiveIntegerField(blank=True, null=True)),
                ("weight_2600g", models.PositiveIntegerField(blank=True, null=True)),
                ("weight_2700g", models.PositiveIntegerField(blank=True, null=True)),
                ("weight_2800g", models.PositiveIntegerField(blank=True, null=True)),
                ("weight_2900g", models.PositiveIntegerField(blank=True, null=True)),
                ("weight_3000g", models.PositiveIntegerField(blank=True, null=True)),
                ("weight_3100g", models.PositiveIntegerField(blank=True, null=True)),
                ("weight_3200g", models.PositiveIntegerField(blank=True, null=True)),
                ("weight_3300g", models.PositiveIntegerField(blank=True, null=True)),
                ("weight_3400g", models.PositiveIntegerField(blank=True, null=True)),
                ("weight_3500g", models.PositiveIntegerField(blank=True, null=True)),
                ("weight_3600g", models.PositiveIntegerField(blank=True, null=True)),
                ("weight_3700g", models.PositiveIntegerField(blank=True, null=True)),
                ("weight_3800g", models.PositiveIntegerField(blank=True, null=True)),
                ("weight_3900g", models.PositiveIntegerField(blank=True, null=True)),
                ("weight_4000g", models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
