# Generated by Django 4.1.6 on 2023-06-19 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("medias", "0001_initial"),
        ("reviews", "0001_initial"),
        ("notifications", "0001_initial"),
        ("products", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="influencer_posting",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="videos",
                to="users.influencerposting",
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="product_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="videos",
                to="products.productpost",
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="users.brand",
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="influencer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="users.influencer",
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="influencer_posting",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="users.influencerposting",
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="notice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="notifications.notice",
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="notification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="notifications.notification",
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="orderclaimhandle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="orders.orderclaimhandle",
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="product_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="products.productpost",
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="reviews",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="reviews.review",
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="userQnA",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="users.userqna",
            ),
        ),
    ]
