# Generated by Django 4.1.6 on 2023-06-26 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("baskets", "0002_initial"),
        ("products", "0002_initial"),
        ("users", "0001_initial"),
        ("coupons", "0002_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("shipments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="preorderitem",
            name="influencer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pre_order_items",
                to="users.influencer",
            ),
        ),
        migrations.AddField(
            model_name="preorderitem",
            name="pre_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="baskets.preorder",
            ),
        ),
        migrations.AddField(
            model_name="preorderitem",
            name="product_post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pre_order_items",
                to="products.productpost",
            ),
        ),
        migrations.AddField(
            model_name="preorder",
            name="influencer_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pre_orders",
                to="users.influencer",
            ),
        ),
        migrations.AddField(
            model_name="preorder",
            name="shipments",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pre_orders",
                to="shipments.shipment",
            ),
        ),
        migrations.AddField(
            model_name="preorder",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pre_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="like",
            name="product_post",
            field=models.ManyToManyField(
                related_name="likes", to="products.productpost"
            ),
        ),
        migrations.AddField(
            model_name="like",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="basketitem",
            name="basket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items_in_basket",
                to="baskets.basket",
            ),
        ),
        migrations.AddField(
            model_name="basketitem",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="coupons.coupon",
            ),
        ),
        migrations.AddField(
            model_name="basketitem",
            name="influencer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="baskets",
                to="users.influencer",
            ),
        ),
        migrations.AddField(
            model_name="basketitem",
            name="product_content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="basketitem",
            name="product_post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="products.productpost",
            ),
        ),
        migrations.AddField(
            model_name="basket",
            name="basket_items",
            field=models.ManyToManyField(
                related_name="baskets", to="baskets.basketitem"
            ),
        ),
        migrations.AddField(
            model_name="basket",
            name="shipments",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="baskets",
                to="shipments.shipment",
            ),
        ),
        migrations.AddField(
            model_name="basket",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="baskets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="basketitem",
            unique_together={("basket", "ref")},
        ),
    ]
