# Generated by Django 4.1.6 on 2023-06-19 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("carts", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("required_participants", models.PositiveIntegerField()),
                ("end_time", models.DateTimeField()),
                ("is_closed", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GroupPurchaseUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderClaimHandle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("claim_amount", models.PositiveIntegerField()),
                (
                    "claim_reason",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("claim_detail", models.TextField(blank=True, null=True)),
                ("claim_answer", models.TextField(blank=True, null=True)),
                ("claim_answer_date", models.DateTimeField(blank=True, null=True)),
                (
                    "claim_account_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "claim_account_bank",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "claim_account_bank_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("claim_date", models.DateTimeField()),
                (
                    "return_scmNo",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_approved", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scmNo", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Paid"),
                            (2, "Ready"),
                            (3, "Shipped"),
                            (4, "Delivered"),
                            (5, "Payment Complete"),
                            (6, "Cancel Requested"),
                            (7, "Exchange Requested"),
                            (8, "Returning"),
                            (9, "Exchanged"),
                            (10, "Refund Requested"),
                            (11, "Refunded"),
                        ],
                        default=1,
                    ),
                ),
                ("refund_amount", models.PositiveIntegerField(default=0)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="orders.order",
                    ),
                ),
                (
                    "pre_order_item",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_item",
                        to="carts.preorderitem",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
