# Generated by Django 4.1.6 on 2023-06-26 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("baskets", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderclaimhandle",
            name="claim_answer_manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_claim_handles_answered",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="orderclaimhandle",
            name="order_items",
            field=models.ManyToManyField(
                blank=True, related_name="order_claim_handles", to="orders.orderitem"
            ),
        ),
        migrations.AddField(
            model_name="orderclaimhandle",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_claim_handles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="pre_order",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order",
                to="baskets.preorder",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="grouppurchaseuser",
            name="group_purchase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="orders.grouppurchase"
            ),
        ),
        migrations.AddField(
            model_name="grouppurchaseuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="grouppurchase",
            name="product_post",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_purchases",
                to="products.productpost",
            ),
        ),
        migrations.AddField(
            model_name="grouppurchase",
            name="users",
            field=models.ManyToManyField(
                related_name="group_purchases",
                through="orders.GroupPurchaseUser",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="grouppurchaseuser",
            unique_together={("user", "group_purchase")},
        ),
    ]
