# Generated by Django 4.1.6 on 2023-06-24 08:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderclaimhandle",
            old_name="orderitems",
            new_name="order_items",
        ),
    ]
