# Generated by Django 4.1.6 on 2023-06-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("purchase_price", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(max_length=255)),
                ("original_price", models.PositiveIntegerField()),
                ("stock_quantity", models.PositiveIntegerField()),
                (
                    "sales_quantity",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                ("sale_price", models.PositiveIntegerField()),
                ("description", models.TextField(blank=True, default="")),
                (
                    "imageurl",
                    models.ImageField(
                        blank=True, null=True, upload_to="product_images"
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("weight", models.PositiveIntegerField(default=0)),
                (
                    "commission",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(default="", max_length=255)),
                ("price_for_1", models.PositiveIntegerField(blank=True, null=True)),
                ("price_for_2", models.PositiveIntegerField(blank=True, null=True)),
                ("price_for_10", models.PositiveIntegerField(blank=True, null=True)),
                ("price_for_50", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "visibility",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("publish_time", models.DateTimeField(blank=True, null=True)),
                ("onsale", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[("NORMAL", "normal"), ("EVENT", "event")],
                        default="NORMAL",
                        max_length=30,
                    ),
                ),
                ("event_start_date", models.DateTimeField(blank=True, null=True)),
                ("event_end_date", models.DateTimeField(blank=True, null=True)),
                ("event_discount", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "is_deleted",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("hit", models.PositiveIntegerField(blank=True, default=0, null=True)),
                (
                    "basket_cnt",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "order_cnt",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                ("seo_data", models.TextField(blank=True, null=True)),
                (
                    "grouppurchase_cnt",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "product",
                    models.ManyToManyField(
                        related_name="product_posts", to="products.product"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
