# Generated by Django 4.1.6 on 2023-06-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_product_sale_price_alter_product_commission_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productpost",
            name="cart_cnt",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="productpost",
            name="grouppurchase_cnt",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="productpost",
            name="hit",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="productpost",
            name="is_deleted",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="productpost",
            name="onsale",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="productpost",
            name="order_cnt",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="productpost",
            name="publish_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productpost",
            name="visibility",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
